paths:
  pdf_dir: data/papers
  cache_dir: data/cache
  out_reviews: outputs/reviews
  out_judges: outputs/judges
  out_jsonl: outputs/aggregates
runtime:
  timezone: "Asia/Tokyo"
  seed: 0                  # informational; model is greedy
  concurrency: 3
  request_timeout_s: 120
models:
  reviewer:
    id: "gpt-5"
    temperature: 0
    top_p: 1
  judge:
    id: "claude"          # J2 primary
limits:
  review_min_words: 600
  review_max_words: 800
  max_pdf_pages: 200
prompts:
  persona_version: "A"
  structure: "Use the ICLR/OpenReview structure: Summary; Strengths; Weaknesses; Questions; Overall [1–10]; Confidence [1–5]. Keep the review to 600–800 words."
mineru:
  enabled: true
  keep_layout: true
  include_appendix: true
vision:
  send_figures: true
  include_captions: true
judging:
  retries: 2
  parse_strict: true
  toxicity_flag_threshold: 5
logging:
  level: INFO
